spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fintech_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: validate  # 개발용: update, 운영용: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  h2:
    console:
      enabled: false  # MySQL 사용시 H2 콘솔 비활성화

logging:
  level:
    com.fintech.server: DEBUG
    org.hibernate.SQL: DEBUG
